language: go
go:
  - 1.9.x
  - master
script:
  - go build -race ./...
  - go test -v -race ./...
  - env GOOS=windows GOARCH=amd64 go build ./... && zip gomir_${TRAVIS_BRANCH}_windows_amd64.zip gomir.exe
  - env GOOS=linux GOARCH=amd64 go build ./... && zip gomir_${TRAVIS_BRANCH}_linux_amd64.zip gomir
  - env GOOS=darwin GOARCH=amd64 go build ./... && zip gomir_${TRAVIS_BRANCH}_darwin_amd64.zip gomir
